### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by StephenJose-Dai** [Rr210/hexo-wx-api#5]
我小程序编译的时候报错了，似乎是没找到vant-weapp/search

![5K9H@K`3THRLHG6 JV295 P](https://github.com/rr210/hexo-wx-api/assets/36736149/abe6bf60-f46a-4174-9ec0-40d8ca5aa625)

**Comment by ryanuo** [comment]
> 我小程序编译的时候报错了，似乎是没找到vant-weapp/search
> 
> ![5K9H@K`3THRLHG6 JV295 P](https://private-user-images.githubusercontent.com/36736149/299177455-abe6bf60-f46a-4174-9ec0-40d8ca5aa625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzA4NjYsIm5iZiI6MTcwNjA3MDU2NiwicGF0aCI6Ii8zNjczNjE0OS8yOTkxNzc0NTUtYWJlNmJmNjAtZjQ2YS00MTc0LTllYzAtNDBkOGNhNWFhNjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA0MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNGI2ZGVmZDNhOTlkMWI4YWJlYmVlNGI2YTM0MGMzZTljYTk1MGU1NjgwODFlNjg3ZTg0MWJiNTAyYTg3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OaCCby3wR-WY6EkKxI-VuYVr0so3s0MwkARpjs4AbEQ)

https://blog.csdn.net/Huang_milk/article/details/118523339

**Comment by StephenJose-Dai** [comment]
我博客图片是相对路径，小程序要改哪里才能显示图片啊？我看小程序都是自己加上https://servicewechat.com，这样导致我图片显示不了报错了
